# pylint: disable=C0103
# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20170804_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='_text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
